version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - docker_backend:/usr/src/app
    command: npm start

  vite-project:
    build:
      context: ./vite-project
    ports:
      - "5173:5173"
    volumes:
      - docker_vite-project:/usr/src/app
    command: npm run dev
    depends_on:
      - backend

volumes:
  docker_backend:
  docker_vite-project:
