version: 2.1

jobs:
  build-backend:
    docker:
      - image: cimg/node:16.13.2
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install backend dependencies
          command: npm install
      - run: echo "hello from backend"

      #- run:
      #  name: Run backend tests
      # command: npm test

  build-vite-project:
    docker:
      - image: cimg/node:16.13.2
    working_directory: ~/project/vite-project
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install vite-project dependencies
          command: npm install
      - run:
          name: Run vite-project build
          command: npm run build
      - run: echo "hello from frontend"
      - run:
          name: Run frontend tests
          command: npm test

workflows:
  version: 2.1
  build_all:
    jobs:
      - build-backend
      - build-vite-project
