version: 2.1

jobs:
  build-backend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install backend dependencies
          command: npm install
      - run:
          name: Run backend tests
          command: npm test

  build-vite-project:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project/vite-project
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install vite-project dependencies
          command: npm install
      - run:
          name: Run vite-project build
          command: npm run build

workflows:
  version: 2
  build_all:
    jobs:
      - build-backend
      - build-vite-project
